# https://bukkit.gamepedia.com/Plugin_YAML
name: racing
version: ${project.version}
description: With Racing you can compete against other players in custom made racing tracks.
author: hornta
website: https://github.com/TrollskogenMC/racing
main: com.github.hornta.racing.RacingPlugin
depend: [ ProtocolLib ]
softdepend: [ NoteBlockAPI, HolographicDisplays, Vault, mcMMO ]
commands:
  racing:
    aliases:
      - rc
permissions:
  racing.admin:
    description: Gives access to everything in Racing plugin
    default: op
    children:
      racing.modify: true
  racing.modify:
    description: Gives access to build and modify races
    default: op
    children:
      racing.moderator: true
  racing.moderator:
    description: Gives access to start and stop races
    default: op
  racing.player:
    description: Gives access to basic commands in Racing
    default: true
api-version: 1.16
